#ifndef MISC_HPP
#define MISC_HPP

#include <string>

namespace cpp_parser
{
    /**
     * Checks for the existance of a file
     * @return true if file exists otherwise false
     */
    bool file_exists(const std::string &file);

    /**
     * Counts the ocurrences of a character on a given string
     * @return The amount of characters found
     */
    unsigned int count_character(const char &character, std::string &source);

    /**
     * The current version of cpp_parser library generated by autoversion system
     */
    std::string version();
};

#endif
